### ISSUE TITLE
Setup blowing up after selecting database from dropdown

### ISSUE THREAD

**Issue by shivinders** [Kentico/ADImport#11]
OS is Windows 10 Enterprise x64 version 1803 build 17134.1.
Trying to run setup for the very first time as local admin. After entering Azure SQL database info, SQL username, establish connection succeeds. Error 1 occurs when database is selected from dropdown. Error 2 occurs when clicking Continue on Error 1.

[error-1-details-May-29-2018.txt](https://github.com/Kentico/ADImport/files/2049189/error-1-details-May-29-2018.txt)
![error-1-may-29-2018](https://user-images.githubusercontent.com/35081461/40671795-7f1bbb48-6332-11e8-851f-7d3efe59eec0.png)
![error-2-may-29-2018](https://user-images.githubusercontent.com/35081461/40671796-7f2771d6-6332-11e8-8ccd-bab7929e186f.png)
[error-2-details-May-29-2018.txt](https://github.com/Kentico/ADImport/files/2049190/error-2-details-May-29-2018.txt)

**Comment by shivinders** [comment]
Adding <loadFromRemoteSources enabled="true"/> to <runtime> in ADImport.exe.config resolved this. Documenting here so someone else can use this. 

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element

**Comment by ZdenekS81** [comment]
I'm closing the issue. We weren't able to reproduce described errors.

The error itself means that some assemblies or files were downloaded from an unsecured source and the solution is to use the mentioned config key **loadFromRemoteSources** or find these assemblies and unblock them manually (right click on the file > Properties > General tab > click Unblock).
