### ISSUE TITLE
Clicking "Select all" or "Delselect all" takes a long time

### ISSUE THREAD

**Issue by shivinders** [Kentico/ADImport#12]
On the "Select users & groups to be imported" dialog box there is an option to "Select all" or "Delselect all".

It takes forever to complete once you click on of these buttons. Ok not forever but several minutes. 

![image](https://user-images.githubusercontent.com/35081461/40851747-ef2b7362-658d-11e8-9a6d-842d2bf5b035.png)

**Comment by petrsvihlik** [comment]
It's true that it can take some time. It depends on how big your AD is. The utility needs to load the whole AD to discover the structure and relations between groups to be able to place them to the right places in the tree structure.
Looking back, it's not an ideal design for large directories with lots of groups...but that's how it is.
