### ISSUE TITLE
Selected username format to be domain\sam but it imported domain-sam

### ISSUE THREAD

**Issue by shivinders** [Kentico/ADImport#15]
Selected username format to be domain\sam but it imported domain-sam. Is this a bug or I did something wrong?

**Comment by petrsvihlik** [comment]
This is intentional. Usernames in Kentico support only characters that are valid in URLs. All invalid characters are replaced with a dash (or a character configurable in web.config).

https://docs.kentico.com/k11/references/reference-web-config-application-keys#Reference-Web.configapplicationkeys-Settingsforforbiddencharactersinuserandrolenames

**Comment by shivinders** [comment]
Kudos to flexibility in Kentico. These options in web.config are amazing! 

My question is how is the replacement of / with - supposed to work with claims based authentication? We have an ADFS server which is sending the samaccountname in the domain\sam format. After running ADImport tool, how will Kentico make a decision that eagle\jdoe the ADFS sends is the same guy as eagle-jdoe that ADImport created?

**Comment by petrsvihlik** [comment]
One solution would be to implement a [custom](https://docs.kentico.com/k11/custom-development/handling-global-events/handling-custom-claims-based-authentication) ([claims-based](https://docs.kentico.com/k11/custom-development/handling-global-events/handling-custom-external-authentication)) authentication module, run the username through [`ValidationHelper.GetSafeUserName()`](http://devnet.kentico.com/docs/11_0/api/html/M_CMS_Helpers_ValidationHelper_GetSafeUserName.htm) method, and match it with user in the database.

**Comment by shivinders** [comment]
But why are we supposed to go through the hassle in the first place  :)
I think it would be easier if the domain name is stripped out from the claim altogether. And ADImport as well.

**Comment by petrsvihlik** [comment]
You can choose to import just [SAM](https://github.com/Kentico/ADImport/wiki/Importing-users-and-roles-from-Active-Directory#step-5--field-mapping) and omit the domain name. Isn't that what you need?
