### ISSUE TITLE
What is the difference in these two options?

### ISSUE THREAD

**Issue by shivinders** [Kentico/ADImport#16]
![image](https://user-images.githubusercontent.com/35081461/43081155-fc2fa974-8e56-11e8-99ff-5cd655a7a883.png)

Update data of existing roles and users
Update roles of existing Active Directory users

**Comment by petrsvihlik** [comment]
See https://github.com/Kentico/ADImport/wiki/Importing-users-and-roles-from-Active-Directory#step-4--import-settings

**Comment by shivinders** [comment]
@petrsvihlik  Thanks for the documentation link!
Maybe it can be changed to this:
Update properties of existing roles and users
Update user-role relationships of existing Active Directory users

**Comment by petrsvihlik** [comment]
@shivinders would you like to submit a pull request?
