### ISSUE TITLE
Pulling AD thumbnail into Kentico User Avatar

### ISSUE THREAD

**Issue by Hungry-Lemon-Daddy** [Kentico/ADImport#19]
Hi,
Does the ADImport support pulling in the user thumbnail image from AD into the Kentico Avatar record for the user? How have other users implemented this?

Thanks
Ian

**Comment by petrsvihlik** [comment]
Hi @Hungry-Lemon-Daddy. Unfortunately, it doesn't.

I'd suggest adjusting the [`CMSImport`](https://github.com/Kentico/ADImport/blob/master/ADImport/CMSImport.cs#L520) class and building your own build of ADImport for the time being. 

The described functionality makes sense to be a part of the tool. If you agree, you can submit a pull request. We'll do a review and eventually merge it. Please let us know if you need any further info.
