### ISSUE TITLE
Import AD groups issue

### ISSUE THREAD

**Issue by stuhealth** [Kentico/ADImport#9]
Hi..
hoping someone can assist with this utility, 
I have run through import utility, authenticated to database and AD domain controller, select groups I wish to import, then throws an error, unhandled exception with no additional details.
Can anyone advise domain functional level required for the import utility ?  don't laugh, but my organisation is still on Win2003 domain controllers  :)
Is this an issue...?

**Comment by petrsvihlik** [comment]
any update on this one @ZdenekS81 ?

**Comment by ZdenekS81** [comment]
Hi @stuhealth,

is the error still present or have you been able to solve it somehow, please?

Best regards,
Zdenek
